//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuGiOh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo()
        {
            this.Cartas = new HashSet<Carta>();
        }
    
        public int IdTipo { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> MonstroId { get; set; }
        public Nullable<int> ArmadilhaId { get; set; }
        public Nullable<int> MagiaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carta> Cartas { get; set; }
        public virtual CrtArmadilha CrtArmadilha { get; set; }
        public virtual CrtMagia CrtMagia { get; set; }
        public virtual CrtMonstro CrtMonstro { get; set; }
    }
}
